tel: "+16135551234"
tel_display: 613 555 1234
seo:
  tagline: Fijn wonen in Rotterdam
location:
  country: England
  locality: Leamington Spa
  region: Warwickshire
  street_address: 1234 Roundabout Way
