backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  - name: "blocken_01" # Used in routes, e.g., /admin/collections/blog
    label: "Blocken 01" # Used in the UI
    folder: "_posts/blocken_01" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Tags", name: "tags", widget: "hidden", default: "block_01"}
      - {label: "Kop", name: "title", widget: "string"}
      - {label: "Foto Bestand", name: "foto_bestand", widget: "image"}
      - {label: "Foto Alt", name: "foto_alt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "carousels_01" 
    label: "Carousels 01"
    folder: "_posts/carousels_01" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Tags", name: "tags", widget: "hidden", default: "carousel_01"}
      - {label: "Foto Bestand", name: "foto_bestand", widget: "image"}
      - {label: "Foto Alt", name: "foto_alt", widget: "string"}
      - {label: "Foto Tekst", name: "foto_tekst", widget: "string"}
  - name: "openingstijd" 
    label: "Openingstijd"
    folder: "_posts/openingstijd" 
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Vakantie", name: "vakantie_tijd", widget: "boolean", default: true}
  - label: "Website settings"
    name: "website-settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"
          - label: "Tel display"
            name: "tel_display"
            widget: "string"
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - label: "Tagline"
                name: "tagline"
                widget: "string"
          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - label: "Street address"
                name: "street_address"
                widget: "string"
              - label: "Locality"
                name: "locality"
                widget: "string"
              - label: "Region"
                name: "region"
                widget: "string"
              - label: "Country"
                name: "country"
                widget: "string"

  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Meta Description",
          name: "meta_description",
          widget: "string",
          required: false,
        }
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Dan Urbanowicz", value: "dan_urbanowicz" }
          - { label: "John Doe", value: "john_doe" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
        }
      - {
          label: "Intro Paragraph",
          name: "intro_paragraph",
          widget: "markdown",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Categories",
          name: "categories",
          widget: "string",
          required: false,
        }
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Meta Description",
          name: "meta_description",
          widget: "string",
          required: false,
        }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - {
          label: "Section",
          name: "section",
          widget: "hidden",
          default: "{{name}}",
        }
      - {
          label: "Intro Paragraph",
          name: "intro_paragraph",
          widget: "markdown",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
